[project]
name = "glassbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "beautifulsoup4>=4.15.0",
    "gradio>=6.28.0",
    "langfuse>=4.15.4",
    "matplotlib>=3.11.2",
    "numpy>=2.5.2",
    "ollama>=0.6.2",
    "python-dotenv>=1.2.3",
    "requests>=2.28.1",
    "torch>=2.11.0",
    "transformer-lens>=4.0.0",
    "transformers>=5.17.0",
]

[project.scripts]
glassbox = "glassbox:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
