"""
Scan the ecosystem for things that may have changed since the plan was written.

    uv run scratch/model_scan.py            # writes research/scan-<date>.md (+ raw JSON alongside)

Sources (all public, no keys):
  - Ollama library: newest models, and models tagged 'tools'; per-model capability tags and tag sizes
  - Hugging Face: trending and newest text-generation models
  - GitHub: latest release of every tool in the plan; recently-starred agent / interpretability repos

Uses only the Python standard library. Polite: small sleeps between requests; GitHub search is limited to
10 requests/minute unauthenticated, so those are spaced out. Whole run ~2-3 minutes.
"""

import datetime
import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

UA = {"User-Agent": "glassbox-scan/0.1 (+https://github.com/brawwwr/glassbox)", "Accept": "*/*"}
OUT_DIR = Path("research")
OUT_DIR.mkdir(exist_ok=True)
STAMP = datetime.date.today().isoformat()
raw = {}


def get(url, timeout=25, as_json=False):
    req = urllib.request.Request(url, headers=UA)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            data = r.read().decode("utf-8", errors="replace")
        return json.loads(data) if as_json else data
    except urllib.error.HTTPError as e:
        return {"_error": f"HTTP {e.code}"} if as_json else f"<!-- HTTP {e.code} -->"
    except Exception as e:
        return {"_error": str(e)[:100]} if as_json else f"<!-- {str(e)[:100]} -->"


md = [f"# Ecosystem scan — {STAMP}", "",
      "Generated by `scratch/model_scan.py` on the home PC. Raw JSON in `research/scan-{STAMP}-*.json`.", ""]

# ---------------------------------------------------------------------------
# 1. Ollama library
# ---------------------------------------------------------------------------
print("Ollama library ...", flush=True)
md += ["## Ollama library", ""]

def ollama_names(html):
    names = re.findall(r'href="/library/([a-z0-9][a-z0-9._\-]*)"', html)
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n); out.append(n)
    return out

newest = ollama_names(get("https://ollama.com/library?sort=newest"))
popular = ollama_names(get("https://ollama.com/library?sort=popular"))
tools_newest = ollama_names(get("https://ollama.com/search?c=tools&o=newest"))
raw["ollama_newest"], raw["ollama_popular"], raw["ollama_tools_newest"] = newest, popular, tools_newest

def ollama_detail(name):
    html = get(f"https://ollama.com/library/{name}")
    caps = sorted(set(re.findall(r'>(tools|thinking|vision|embedding|cloud)<', html)))
    # tag rows look like: /library/<name>:<tag> ... <size>GB
    tags = re.findall(rf'/library/{re.escape(name)}:([a-z0-9._\-]+)"[^<]*<[^>]*>[^<]*</[^>]*>\s*(?:<[^>]*>\s*)*([0-9.]+\s?[GM]B)', html)
    if not tags:
        tags = re.findall(rf'/library/{re.escape(name)}:([a-z0-9._\-]+)', html)
        tags = [(t, "") for t in dict.fromkeys(tags)]
    sizes = re.findall(r'([0-9.]+\s?[GM]B)', html)
    pulls = re.search(r'([0-9.,]+[KM]?)\s*(?:Pulls|pulls)', html)
    desc = re.search(r'<meta name="description" content="([^"]*)"', html)
    return {"name": name, "capabilities": caps, "tags": tags[:12], "sizes_seen": sorted(set(sizes))[:12],
            "pulls": pulls.group(1) if pulls else "", "description": (desc.group(1) if desc else "")[:200]}

details = {}
for n in (newest[:30] + [x for x in tools_newest[:30] if x not in newest[:30]]):
    details[n] = ollama_detail(n)
    time.sleep(0.4)
raw["ollama_details"] = details

md += ["### Newest 30 (library sort=newest)", "", "| model | capabilities | pulls | sizes seen | description |", "|---|---|---|---|---|"]
for n in newest[:30]:
    d = details.get(n, {})
    md.append(f"| `{n}` | {', '.join(d.get('capabilities', []))} | {d.get('pulls','')} | {', '.join(d.get('sizes_seen', [])[:6])} | {d.get('description','')[:110]} |")
md += ["", "### Newest with the `tools` capability (search?c=tools&o=newest)", "", "| model | capabilities | pulls | sizes seen |", "|---|---|---|---|"]
for n in tools_newest[:30]:
    d = details.get(n, {})
    md.append(f"| `{n}` | {', '.join(d.get('capabilities', []))} | {d.get('pulls','')} | {', '.join(d.get('sizes_seen', [])[:6])} |")
md += ["", "### Most popular 25 (for reference)", "", ", ".join(f"`{n}`" for n in popular[:25]), ""]

# our current models: re-check capabilities
ours = ["qwen3", "ornith", "gpt-oss", "gemma4", "muse-glimmer", "qwen3.8"]
md += ["### Our current models, re-checked", "", "| model | capabilities | pulls | tags (first 8) |", "|---|---|---|---|"]
for n in ours:
    d = ollama_detail(n); raw[f"ours_{n}"] = d; time.sleep(0.4)
    md.append(f"| `{n}` | {', '.join(d['capabilities'])} | {d['pulls']} | {', '.join(t for t, _ in d['tags'][:8])} |")
md.append("")

# ---------------------------------------------------------------------------
# 2. Hugging Face
# ---------------------------------------------------------------------------
print("Hugging Face ...", flush=True)
md += ["## Hugging Face — text-generation", ""]
for label, url in [
    ("Trending", "https://huggingface.co/api/models?pipeline_tag=text-generation&sort=trendingScore&direction=-1&limit=40"),
    ("Newest with >200 likes", "https://huggingface.co/api/models?pipeline_tag=text-generation&sort=createdAt&direction=-1&limit=100"),
]:
    data = get(url, as_json=True)
    raw[f"hf_{label}"] = data
    md += [f"### {label}", "", "| model | likes | downloads | created |", "|---|---|---|---|"]
    if isinstance(data, list):
        rows = data if label == "Trending" else [m for m in data if m.get("likes", 0) > 200]
        for m in rows[:40]:
            md.append(f"| `{m.get('id')}` | {m.get('likes','')} | {m.get('downloads','')} | {str(m.get('createdAt',''))[:10]} |")
    else:
        md.append(f"| error | {data} | | |")
    md.append("")
    time.sleep(1)

# ---------------------------------------------------------------------------
# 3. GitHub — releases of every tool in the plan, then recent repos
# ---------------------------------------------------------------------------
print("GitHub releases ...", flush=True)
md += ["## GitHub — latest releases of the plan's tools", "", "| repo | latest release | published | notes |", "|---|---|---|---|"]
repos = [
    ("ollama/ollama", "serving"), ("langfuse/langfuse", "macro lens"), ("langfuse/langfuse-python", "SDK"),
    ("TransformerLensOrg/TransformerLens", "micro lens"), ("ndif-team/nnsight", "micro lens alt"),
    ("TransformerLensOrg/CircuitsVis", "attention viz"), ("Arize-ai/phoenix", "tracing alt"),
    ("promptfoo/promptfoo", "evals"), ("UKGovernmentBEIS/inspect_ai", "evals alt"),
    ("modelcontextprotocol/python-sdk", "MCP"), ("modelcontextprotocol/inspector", "MCP"),
    ("gradio-app/gradio", "UI"), ("astral-sh/uv", "python env"), ("ollama/ollama-python", "client"),
    ("NousResearch/hermes-agent", "Phase 7 specimen"), ("openclaw/openclaw", "Phase 7 specimen"),
    ("ggml-org/llama.cpp", "under Ollama"), ("huggingface/transformers", "Phase 4"),
]
for repo, note in repos:
    rel = get(f"https://api.github.com/repos/{repo}/releases/latest", as_json=True)
    if isinstance(rel, dict) and "tag_name" in rel:
        md.append(f"| `{repo}` | {rel['tag_name']} | {str(rel.get('published_at',''))[:10]} | {note} |")
    else:
        info = get(f"https://api.github.com/repos/{repo}", as_json=True)
        if isinstance(info, dict) and "pushed_at" in info:
            md.append(f"| `{repo}` | (no releases) | last push {str(info['pushed_at'])[:10]}, ★{info.get('stargazers_count','')} | {note} |")
        else:
            md.append(f"| `{repo}` | not found / rate-limited | | {note} |")
    raw[f"gh_{repo}"] = rel
    time.sleep(0.8)
md.append("")

print("GitHub search (slow, rate-limited) ...", flush=True)
md += ["## GitHub — recently active repos (created or pushed since 2026-06-01, by stars)", ""]
searches = [
    ("LLM agents, new since June", "llm agent created:>2026-06-01 stars:>200"),
    ("Tool-calling / function-calling", "function calling llm tools pushed:>2026-08-01 stars:>300"),
    ("Mechanistic interpretability", "mechanistic interpretability pushed:>2026-06-01 stars:>100"),
    ("Attention / logit lens visualisation", "logit lens OR attention visualization transformer pushed:>2026-06-01 stars:>50"),
    ("LLM observability / tracing", "llm observability tracing pushed:>2026-08-01 stars:>500"),
    ("Local agents on Ollama", "ollama agent created:>2026-06-01 stars:>100"),
    ("MCP servers", "mcp server created:>2026-07-01 stars:>300"),
    ("LLM evals", "llm evaluation framework pushed:>2026-08-01 stars:>500"),
]
for label, q in searches:
    url = "https://api.github.com/search/repositories?q=" + urllib.request.quote(q) + "&sort=stars&order=desc&per_page=12"
    data = get(url, as_json=True)
    raw[f"ghsearch_{label}"] = data
    md += [f"### {label}", "", "| repo | ★ | pushed | description |", "|---|---|---|---|"]
    items = data.get("items", []) if isinstance(data, dict) else []
    if not items:
        md.append(f"| (none / rate-limited: {data.get('message','') if isinstance(data, dict) else data}) | | | |")
    for it in items:
        md.append(f"| [`{it['full_name']}`]({it['html_url']}) | {it['stargazers_count']} | {it['pushed_at'][:10]} | {(it.get('description') or '')[:120]} |")
    md.append("")
    time.sleep(7)          # 10 search requests / minute unauthenticated

# ---------------------------------------------------------------------------
# write
# ---------------------------------------------------------------------------
out_md = OUT_DIR / f"scan-{STAMP}.md"
out_md.write_text("\n".join(md), encoding="utf-8")
(OUT_DIR / f"scan-{STAMP}-raw.json").write_text(json.dumps(raw, indent=1, default=str)[:4_000_000], encoding="utf-8")
print(f"\nwrote {out_md} ({len(md)} lines) and raw JSON. Commit and push; Claude reads it from the Mac clone.")
